### ISSUE TITLE
Remove phases implementation of temporal memory

### ISSUE THREAD

**Issue by subutai** [numenta/nupic.research#600]
We wish to remove the phases implementation of temporal memory from the repository. This is a super issue to collect the various items needed before we can do that.

- [x]   [Update the Python ETM to use the new "walk the columns" strategy](https://github.com/numenta/nupic.research/issues/598) 

- [x] [Convert sequence_learning to new TM](https://github.com/numenta/nupic.research/issues/601)

- [x] [Port bug fixes in temporal_memory_phases to new temporal_memory](https://github.com/numenta/nupic.research/issues/603)

- [x] [Remove _phases files](https://github.com/numenta/nupic.research/issues/602)

**Comment by mrcslws** [comment]
@subutai all done!

I'll let you close this super issue. 🙂

**Comment by subutai** [comment]
@mrcslws Great!!
